<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Thread: <?php echo htmlspecialchars($thread->getSubject()); ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .email-thread-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .thread-header {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            border-left: 4px solid #007bff;
        }
        .message-item {
            background: white;
            border: 1px solid #dee2e6;
            border-radius: 8px;
            margin-bottom: 15px;
            overflow: hidden;
        }
        .message-header {
            background: #f8f9fa;
            padding: 15px;
            border-bottom: 1px solid #dee2e6;
        }
        .message-content {
            padding: 20px;
            line-height: 1.6;
        }
        .message-meta {
            font-size: 0.875rem;
            color: #6c757d;
        }
        .thread-nav {
            position: sticky;
            top: 20px;
            background: white;
            padding: 15px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div class="email-thread-container">
        <div class="thread-header">
            <h1 class="h3 mb-2"><?php echo htmlspecialchars($thread->getSubject()); ?></h1>
            <div class="thread-meta">
                <small class="text-muted">
                    Conversation with <?php echo htmlspecialchars($thread->getLead() ? ($thread->getLead()->getName() ?: $thread->getLead()->getEmail()) : 'Unknown'); ?>
                    | <?php echo count($messages); ?> message<?php echo count($messages) !== 1 ? 's' : ''; ?>
                    | Started <?php echo $thread->getFirstMessageDate()->format('M j, Y'); ?>
                </small>
            </div>
        </div>

        <div class="messages-container">
            <?php if (empty($messages)): ?>
                <div class="alert alert-info">
                    <h5>No messages found</h5>
                    <p class="mb-0">This conversation thread doesn't contain any messages yet.</p>
                </div>
            <?php else: ?>
                <?php foreach ($messages as $index => $message): ?>
                    <div class="message-item">
                        <div class="message-header">
                            <div class="d-flex justify-content-between align-items-start">
                                <div>
                                    <h6 class="mb-1"><?php echo htmlspecialchars($message->getSubject()); ?></h6>
                                    <div class="message-meta">
                                        From: <strong><?php echo htmlspecialchars($message->getFromName() ?: $message->getFromEmail()); ?></strong>
                                    </div>
                                </div>
                                <div class="text-end">
                                    <small class="text-muted">
                                        <?php echo $message->getDateSent()->format('M j, Y \a\t g:i A'); ?>
                                    </small>
                                    <br>
                                    <span class="badge bg-secondary"><?php echo ucfirst($message->getEmailType()); ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="message-content">
                            <?php echo $message->getContent(); ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

        <div class="thread-footer mt-4">
            <div class="alert alert-light">
                <small class="text-muted">
                    This email conversation thread was generated by Mautic Email Threads plugin.
                    Thread ID: <code><?php echo htmlspecialchars($thread->getThreadId()); ?></code>
                </small>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
