<?php

return [
    // General
    'mautic.emailthreads.threads' => 'Email Threads',
    'mautic.emailthreads.thread' => 'Email Thread',
    'mautic.emailthreads.plugin.name' => 'Email Threads',
    'mautic.emailthreads.plugin.description' => 'Display emails sent from Mautic as conversation threads on the recipient\'s end',

    // Menu and Navigation
    'mautic.emailthreads.menu.index' => 'Email Threads',
    'mautic.emailthreads.threads.list' => 'Email Threads List',
    'mautic.emailthreads.thread.view' => 'View Thread: %subject%',
    'mautic.emailthreads.view_public' => 'View Public Thread',

    // Permissions
    'mautic.emailthreads.permissions.emailthreads' => 'Email Threads',
    'mautic.emailthreads.permissions.config' => 'Configuration',

    // Thread Properties
    'mautic.emailthreads.thread.id' => 'Thread ID',
    'mautic.emailthreads.thread.subject' => 'Subject',
    'mautic.emailthreads.thread.lead' => 'Contact',
    'mautic.emailthreads.thread.messages' => 'Messages',
    'mautic.emailthreads.thread.message_count' => 'Message Count',
    'mautic.emailthreads.thread.first_message' => 'First Message',
    'mautic.emailthreads.thread.last_message' => 'Last Message',
    'mautic.emailthreads.thread.status' => 'Status',
    'mautic.emailthreads.thread.details' => 'Thread Details',

    // Messages
    'mautic.emailthreads.message.from' => 'From',
    'mautic.emailthreads.message.to' => 'To',
    'mautic.emailthreads.message.date_sent' => 'Date Sent',
    'mautic.emailthreads.message.type' => 'Type',
    'mautic.emailthreads.message.content' => 'Content',

    // Actions
    'mautic.emailthreads.view' => 'View',
    'mautic.emailthreads.edit' => 'Edit',
    'mautic.emailthreads.delete' => 'Delete',
    'mautic.emailthreads.close' => 'Close',
    'mautic.emailthreads.open' => 'Open',
    'mautic.emailthreads.refresh' => 'Refresh',
    'mautic.emailthreads.search' => 'Search',
    'mautic.emailthreads.filter' => 'Filter',

    // Status
    'mautic.emailthreads.status.active' => 'Active',
    'mautic.emailthreads.status.inactive' => 'Inactive',
    'mautic.emailthreads.unknown_lead' => 'Unknown Contact',

    // Configuration
    'mautic.emailthreads.config.enabled' => 'Enable Email Threads',
    'mautic.emailthreads.config.domain' => 'Domain',
    'mautic.emailthreads.config.auto_thread' => 'Auto Threading',
    'mautic.emailthreads.config.thread_lifetime' => 'Thread Lifetime (days)',
    'mautic.emailthreads.config.include_unsubscribe' => 'Include Unsubscribe Link',

    // Email Types
    'mautic.emailthreads.email_type.campaign' => 'Campaign',
    'mautic.emailthreads.email_type.broadcast' => 'Broadcast',
    'mautic.emailthreads.email_type.transactional' => 'Transactional',
    'mautic.emailthreads.email_type.manual' => 'Manual',

    // Public Interface
    'mautic.emailthreads.public.conversation_with' => 'Conversation with %name%',
    'mautic.emailthreads.public.thread_footer' => 'This email conversation thread was generated by Mautic Email Threads plugin.',
    'mautic.emailthreads.public.thread_not_found' => 'Thread not found or inactive',

    // Cleanup
    'mautic.emailthreads.cleanup.deactivated' => 'Deactivated %count% expired threads',
    'mautic.emailthreads.cleanup.error' => 'Error during cleanup: %message%',
];
